<script>
var AlteredDB = {
    baseUrl:         <?= json_encode(BASE_URL) ?>,
    pluginAssetsUrl: <?= json_encode($pluginAssetsUrl) ?>,
    cdnUrl:    <?= json_encode(CDN_URL) ?>,
    lang:         <?= json_encode($lang) ?>,
    uniqueLocale: <?= json_encode($uniqueLocale) ?>,
    uiLang:       <?= json_encode($uiLang) ?>,
    csrfToken: <?= json_encode(csrfToken()) ?>,
    ownAltArt: <?= json_encode($ownAltArtCfg) ?>,
    deckId:    <?= json_encode($editDeckId) ?>,
    isGuest:   <?= $isGuest ? 'true' : 'false' ?>,
    debug:     <?= (defined('API_RESPONSE_DEBUG') && API_RESPONSE_DEBUG) ? 'true' : 'false' ?>,
    factions:  <?= json_encode($factionsData) ?>,
    formats:   <?= json_encode($formatsData) ?>,
    sets:      <?= json_encode($setsData) ?>,
    rarities:  <?= json_encode($raritiesData) ?>,
    types:        <?= json_encode($typesData) ?>,
    typesMerged:  <?= json_encode($typesMergedData) ?>,
    powers:    <?= json_encode($powersData) ?>,
    txt: <?= json_encode([
        'loading'       => $txt['loading'],
        'no_results'    => $txt['no_results'],
        'add_card'      => $txt['add_card'],
        'deck_cards'    => $txt['deck_cards'],
        'hero_required'     => $txt['hero_required'],
        'min_cards'         => $txt['min_cards'],
        'max_cards'         => $txt['max_cards'],
        'max_rare'          => $txt['max_rare'],
        'max_exalted'       => $txt['max_exalted'],
        'max_unique'        => $txt['max_unique'],
        'max_copies'        => $txt['max_copies'],
        'max_copies_rarity' => $txt['max_copies_rarity'],
        'same_faction'      => $txt['same_faction'],
        'validation_ok'     => $txt['validation_ok'],
        'deck_invalid'         => $txt['deck_invalid'],
        'rules_modal_title'    => $txt['rules_modal_title'],
        'rule_hero'            => $txt['rule_hero'],
        'rule_min_cards'       => $txt['rule_min_cards'],
        'rule_max_cards'       => $txt['rule_max_cards'],
        'rule_max_rare'        => $txt['rule_max_rare'],
        'rule_max_exalted'     => $txt['rule_max_exalted'],
        'rule_max_unique'      => $txt['rule_max_unique'],
        'rule_copies'          => $txt['rule_copies'],
        'rule_copies_rarity'   => $txt['rule_copies_rarity'],
        'rule_unique_copies'   => $txt['rule_unique_copies'],
        'rule_same_faction'    => $txt['rule_same_faction'],
        'rule_no_banned'       => $txt['rule_no_banned'],
        'rule_no_suspended'    => $txt['rule_no_suspended'],
        'rule_frontier_legal'  => $txt['rule_frontier_legal'],
        'rule_set_legal'       => $txt['rule_set_legal'],
        'tt_show_banned_suspended'    => $txt['tt_show_banned_suspended'],
        'tt_banned_suspended_allowed' => $txt['tt_banned_suspended_allowed'],
        'unique_not_allowed'   => $txt['unique_not_allowed'],
        'saving'        => $txt['saving'],
        'saved_ok'      => $txt['saved_ok'],
        'save_btn'      => $txt['save_btn'],
        'change_hero'   => $txt['change_hero'],
        'hero_confirm'  => $txt['hero_confirm'],
        'choose_token_arts_btn' => $txt['choose_token_arts_btn'],
        'token_arts_title'      => $txt['token_arts_title'],
        'token_arts_warning'    => $txt['token_arts_warning'],
        'token_arts_empty'      => $txt['token_arts_empty'],
        'token_arts_close'      => $txt['token_arts_close'],
        'token_save_error'      => $txt['token_save_error'],
        'choose_illustration'   => $txt['choose_illustration'],
        'illustration_confirm'  => $txt['illustration_confirm'],
        'no_other_illustration' => $txt['no_other_illustration'],
        'alt_art_stock_warn'    => $txt['alt_art_stock_warn'],
        'choose_hero'   => $txt['choose_hero'],
        'hero_slot'     => $txt['hero_slot'],
        'new_deck'      => $txt['new_deck'],
        'wizard_change'   => $txt['wizard_change'],
        'wizard_create'   => $txt['wizard_create'],
        'wizard_creating' => $txt['wizard_creating'],
        'wizard_hero_req' => $txt['wizard_hero_req'],
        'wizard_name_req' => $txt['wizard_name_req'],
        'wizard_fmt_req'  => $txt['wizard_fmt_req'],
        'wizard_anyway'   => $txt['wizard_anyway'],
        'bga_ok'            => $txt['bga_ok'],
        'bga_fmt_ko'        => $txt['bga_fmt_ko'],
        'bga_hero_ko'       => $txt['bga_hero_ko'],
        'bga_hero_partial'  => $txt['bga_hero_partial'],
        'bga_hero_title'    => $txt['bga_hero_title'],
        'bga_partial_title' => $txt['bga_partial_title'],
        'types'         => $txt['types'],
        'status_auto'   => $txt['status_auto'],
        'status_draft'  => $txt['status_draft'],
        'status_final'  => $txt['status_final'],
        'prev'          => $txt['prev'],
        'next'          => $txt['next'],
        'tab_cards'     => $txt['tab_cards'],
        'tab_stats'     => $txt['tab_stats'],
        'tab_grid'      => $txt['tab_grid'],
        'stats_cost_main'   => $txt['stats_cost_main'],
        'stats_cost_recall' => $txt['stats_cost_recall'],
        'stats_types'       => $txt['stats_types'],
        'stats_powers'      => $txt['stats_powers'],
        'no_cards'      => $txt['no_cards'],
        'err_api'        => $txt['err_api'],
        'save_retry'     => $txt['save_retry'],
        'unsaved_title'  => $txt['unsaved_title'],
        'unsaved_msg'    => $txt['unsaved_msg'],
        'save_and_leave' => $txt['save_and_leave'],
        'leave_anyway'   => $txt['leave_anyway'],
        'stay'           => $txt['stay'],
        'autosaved'      => $txt['autosaved'],
        'guest_saved_ok' => $txt['guest_saved_ok'],
        'show_promo'     => $txt['show_promo'],
        'lbl_variation'  => $txt['lbl_variation'],
        'unnamed'        => $txt['unnamed'],
        'stock_warn'     => $txt['stock_warn'],
        'detail_label'   => $txt['detail_label'],
        'tab_deck'       => $txt['tab_deck'],
    ]) ?>,
    rendererSrc: 'https://cdn.jsdelivr.net/gh/PolluxTroy0/Altered-Card-Renderer@main/altered-card-renderer-minified.js',
    existingDeck: <?= json_encode($existingDeck) ?>,
    collection:        <?= json_encode($_userCollection) ?>,
    collectionEntries: <?= json_encode($_collEntries) ?>, // {ref: api_entry_id}
    collectionMode:    <?= $_collectionMode ? 'true' : 'false' ?>,
    showStockWarn:     <?= $showStockWarn ? 'true' : 'false' ?>,
    collectionUrl:     <?= json_encode(BASE_URL . '/pages/collection') ?>,
    collectionCsrf:    <?= json_encode($_collectionMode ? csrfToken() : '') ?>,
    collApiUrl:        <?= json_encode($_collectionMode ? BASE_URL . '/papi/core-altered-cards/collection-search' : '') ?>,
    favoritesEnabled:  <?= $_favMode ? 'true' : 'false' ?>,
    favoritesData:     <?= json_encode($_favMode ? (object)$_userFavorites : (object)[]) ?>,
    favoritesCsrf:     <?= json_encode($_favMode ? csrfToken() : '') ?>,
    favToggleUrl:      <?= json_encode($_favMode ? BASE_URL . '/papi/core-altered-cards/favorites-toggle' : '') ?>,
    favApiUrl:         <?= json_encode($_favMode ? BASE_URL . '/papi/core-altered-cards/favorites-search' : '') ?>,
    favoriteLabel:     <?= json_encode($uiLang === 'fr' ? 'Favori' : 'Favorite') ?>,
    heroTypes:      <?= json_encode($_heroTypes) ?>,
    heroRarities:   <?= json_encode($_heroRarities) ?>,
    heroSets:       <?= json_encode($_heroSets) ?>,
    heroVariations: <?= json_encode($_heroVariations) ?>,
    heroSort1:           <?= json_encode($_heroSort1) ?>,
    heroSort2:           <?= json_encode($_heroSort2) ?>,
    heroReferenceFilter: <?= json_encode($_heroReferenceFilter) ?>,
    heroSortAlpha:       <?= json_encode($_heroSortAlpha) ?>,
    heroNoDuplicate:     <?= json_encode($_heroNoDuplicate) ?>,
    heroDuplicateOrder:  <?= json_encode($_heroDuplicateOrder) ?>,
    heroDefaultFaction:  <?= json_encode($_heroDefaultFaction) ?>,
    // Creation flow: no ?id= and a usable builder means this is a brand-new deck,
    // so the wizard opens on step 1 instead of dropping the user into an empty
    // builder where the deck's own fields are easy to miss.
    newDeckFlow: <?= (!$editDeckId && ($isGuest || $token)) ? 'true' : 'false' ?>,
    decksUrl:    <?= json_encode(BASE_URL . '/pages/decks') ?>,
    // Sets absent from Board Game Arena (EOLE, FUGUE and their sub-editions).
    setsBga: <?= json_encode(array_map(fn($s) => ($s['bgalegal'] ?? true) !== false, $setsData)) ?>,
    defaultVariations: <?= json_encode($_defaultVariations) ?>,
    setOptionsJson:     <?= $setOptionsJson ?>,
    subtypeOptionsJson:   <?= $subtypeOptionsJson ?>,
    keywordOptionsJson:   <?= $keywordOptionsJson ?>,
    variationOptionsJson: <?= $variationOptionsJson ?>,
    // Flat list of every variation code, used by the hero picker's "Alt arts"
    // toggle to broaden its fetch to all printings.
    allVariations: <?= json_encode(array_column(json_decode($variationOptionsJson, true) ?: [], 'value')) ?>,
    defaultCollection:    <?= json_encode($defaultCollection) ?>,
<?php
    // Promo set linking (main edition → its promo sub editions) + flat sub list.
    $setChildren = [];
    $subSets     = [];
    foreach ($setsData as $_sref => $_sd) {
        if (($_sd['subtype'] ?? '') !== 'sub') continue;
        $subSets[] = $_sref;
        if (!empty($_sd['parent'])) $setChildren[$_sd['parent']][] = $_sref;
    }
    // Sets the uniques API rejects outright (HTTP 400) — see card-search.js.
    $noUniqueSets = array_keys(array_filter($setsData, fn($s) => ($s['uniques'] ?? true) === false));
?>
    setChildren:  <?= json_encode($setChildren) ?>,
    subSets:      <?= json_encode($subSets) ?>,
    noUniqueSets: <?= json_encode(array_values($noUniqueSets)) ?>,
    ownershipApiUrl: <?= json_encode($_ownMode ? BASE_URL . '/papi/core-altered-cards/ownership-search' : '') ?>,
    altArtsUrl:      <?= json_encode($_ownMode ? BASE_URL . '/papi/core-altered-cards/deck-alt-arts' : '') ?>,
    altArtGlobalMode: <?= json_encode($_altArtGlobalMode) ?>,
    altArtSearchUrl: <?= json_encode($_ownMode ? BASE_URL . '/papi/ownership/alt-art-search' : '') ?>,
    altArtCdnUrl:    <?= json_encode(CDN_URL) ?>,
    altArtMarkerImg: <?= json_encode(BASE_URL . '/plugins/ownership/assets/selected_alt.png') ?>,
    altArtSetPreferenceUrl: <?= json_encode($_ownMode ? BASE_URL . '/papi/ownership/alt-art-set-preference' : '') ?>,
    uniquesApiBase:  <?= json_encode(defined('UNIQUES_API_URL') ? UNIQUES_API_URL : '') ?>,
    cardsApiMaxPerPage: <?= (int) CARDS_API_MAX_PER_PAGE ?>,
    cardsDisplayPerPage: <?= (int) CARDS_DISPLAY_PER_PAGE ?>,
    cardDetailBase: <?= json_encode(BASE_URL . '/pages/card') ?>,
    defaultDeckTypes: <?= json_encode($_defaultDeckTypes) ?>,
    uniqueExtraSets: <?= json_encode(array_values(array_intersect(['COREKS'], $validSets))) ?>,
    searchDefaults: <?= json_encode([
        'factions'   => $defaultFactions,
        'types'      => $defaultTypes,
        'rarities'   => $defaultRarities,
        'sets'       => $defaultSets,
        'variations' => $_defaultVariations,
        'sort1'      => $defaultSort1,
        'sort2'      => $defaultSort2,
        'cols'       => (int)$_defaultDbCols,
        'perPage'    => CARDS_DISPLAY_PER_PAGE,
    ]) ?>,
    searchInitial: <?= json_encode([
        'faction'         => $_existingHeroFaction ? [$_existingHeroFaction] : $defaultFactions,
        'factionExplicit' => (bool)$_existingHeroFaction,
        'type'            => $_defaultDeckTypes,
        'typeExplicit'    => true,
        'rarity'          => $defaultRarities,
        'rarityExplicit'  => false,
    ]) ?>,
    handLang: <?= json_encode($uiLang) ?>,
    handTypeLabels: <?= json_encode($txt['types'], JSON_HEX_TAG | JSON_UNESCAPED_UNICODE) ?>,
    handOddsTxt: <?= json_encode([
        'both' => $txt['nc_both'],
        'ratio' => $txt['ho_ratio'],
        'ratioGeneric' => $txt['ho_ratio_generic'],
        'card' => $txt['ohs_card'],
        'cards' => $txt['ohs_cards'],
        'play' => $txt['ohs_play'],
        'plays' => $txt['ohs_plays'],
        'expNone' => $txt['ohs_b4_none'],
        'expOne' => $txt['ohs_b4_one'],
        'expBoth' => $txt['ohs_b4_both'],
    ], JSON_HEX_TAG | JSON_UNESCAPED_UNICODE) ?>,
    handTxt: <?= json_encode([
        'empty' => $txt['hand_empty'],
        'characters' => $txt['hand_characters'],
        'spells' => $txt['hand_spells'],
        'permanents' => $txt['hand_permanents'],
        'avgCost' => $txt['hand_avg_cost'],
        'manaList' => $txt['pt_mana_list'],
        'toMana' => $txt['pt_to_mana'],
        'playBoard' => $txt['pt_play_board'],
        'zoom' => $txt['pt_zoom'],
        'cancel' => $txt['pt_cancel'],
        'discard' => $txt['pt_discard'],
        'returnHand' => $txt['pt_return_hand'],
        'boardList' => $txt['pt_board_list'],
        'discardList' => $txt['pt_discard_list'],
    ], JSON_HEX_TAG | JSON_UNESCAPED_UNICODE) ?>,
};
</script>
